language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - pypy

env:
  - DJANGO=django<1.6
  - DJANGO=django<1.7
  - DJANGO=https://github.com/django/django/tarball/master

matrix:
  include:
    - python: 2.6
      env: DJANGO=django<1.6


install:
  - pip install $DJANGO
  - pip install .

script:
  - django-admin.py --version
  - py.test
